version: "2"
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - revive
    - ineffassign
    - bodyclose
    - sqlclosecheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
