// Closed vocabulary of API error codes across Fase 0, 1, 3, 4, and 7.
// Kept strictly synchronized with backend internal/httpx/errors.go.
// A Record<ApiErrorCode, ErrorPresentation> mapping ensures tsc catches any unmapped code.

export type ApiErrorCode =
    // Base catalog - Fase 0 § 2.6
    | "BAD_REQUEST"
    | "UNAUTHENTICATED"
    | "FORBIDDEN"
    | "NOT_FOUND"
    | "CONFLICT"
    | "PAYLOAD_TOO_LARGE"
    | "UNSUPPORTED_MEDIA_TYPE"
    | "VALIDATION_ERROR"
    | "RATE_LIMITED"
    | "INTERNAL_ERROR"
    | "UPSTREAM_ERROR"
    | "SERVICE_UNAVAILABLE"
    | "UPSTREAM_TIMEOUT"

    // Auth & RBAC - Fase 1
    | "INVALID_CREDENTIALS"
    | "INVALID_REFRESH_TOKEN"
    | "REFRESH_TOKEN_REUSED"
    | "EMPLOYEE_NUMBER_TAKEN"
    | "EMPLOYEE_HAS_ACTIVE_USER"
    | "EMAIL_TAKEN"
    | "EMPLOYEE_ALREADY_HAS_USER"
    | "ROLE_NAME_TAKEN"
    | "ROLE_IN_USE"
    | "SYSTEM_ROLE_IMMUTABLE"
    | "ROLE_ESCALATION_DENIED"
    | "LAST_SUPER_ADMIN"
    | "CSRF_HEADER_MISSING"
    | "CSRF_UNTRUSTED_ORIGIN"

    // Biometrics & Consent - Fase 3
    | "CONSENT_REQUIRED"
    | "CONSENT_ALREADY_GRANTED"
    | "CONSENT_VERSION_OUTDATED"
    | "FACE_NOT_USABLE"
    | "DUPLICATE_PHOTO"
    | "ENROLLMENT_INCOMPLETE"
    | "ENROLLMENT_LIMIT_REACHED"
    | "ENROLLMENT_SESSION_EXPIRED"
    | "ENROLLMENT_MODEL_CHANGED"
    | "FACE_BELONGS_TO_ANOTHER_EMPLOYEE"
    | "REINDEX_IN_PROGRESS"
    | "ATTENDANCE_MODE_MANUAL"

    // Attendance & Verification - Fase 4 & 7
    | "FACE_NOT_ENROLLED"
    | "FACE_NOT_MATCHED"
    | "FACE_MISMATCH"
    | "OUTSIDE_GEOFENCE"
    | "LOCATION_REQUIRED"
    | "LOCATION_INACCURATE"
    | "ALREADY_CHECKED_IN"
    | "ALREADY_CHECKED_OUT"
    | "CHECKOUT_WITHOUT_CHECKIN"
    | "CHECKOUT_TOO_SOON"
    | "ATTENDANCE_ALREADY_REVIEWED"
    | "SELF_REVIEW_DENIED"
    | "EMPLOYEE_INACTIVE"
    | "TOO_MANY_FAILED_ATTEMPTS"
    | "ATTENDANCE_NOT_CONFIGURED"
    | "FACE_SERVICE_NOT_CONFIGURED"
    | "LIVENESS_REQUIRED";
